services:
  python:
    container_name: climate_project
    build:
      context: ..
      dockerfile: docker/dockerfile
    volumes:
      - ..:/app
    working_dir: /app
    ports:
      - "8888:8888"
    depends_on:
      - mongodb
    networks:
      - climate_network
  
  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - climate_network

  spark-master:
    image: bitnami/spark:latest
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_SUBMIT_ARGS=--packages ${SPARK_MONGO_CONNECTOR}
    ports:
      - "7077:7077"  
      - "8080:8080"   
    networks:
      - climate_network
    mem_limit: 1G
    cpus: 1.5

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark_worker_1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark_master:7077
      - SPARK_SUBMIT_ARGS=--packages org.mongodb.spark:mongo-spark-connector_2.12:10.2.0
    depends_on:
      - spark-master
    ports:
      - "8082:8081" 
    networks:
      - climate_network
    mem_limit: 1G
    cpus: 1.5

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark_worker_2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark_master:7077
    depends_on:
      - spark-master
    ports:
      - "8083:8081" 
    networks:
      - climate_network
    mem_limit: 1G
    cpus: 1.5

volumes:
  mongo_data:

networks:
  climate_network: